// +build !ignore_autogenerated

/* Copyright (C) Couchbase, Inc 2020 - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardClient) DeepCopyInto(out *DashboardClient) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardClient.
func (in *DashboardClient) DeepCopy() *DashboardClient {
	if in == nil {
		return nil
	}
	out := new(DashboardClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputParamtersSchema) DeepCopyInto(out *InputParamtersSchema) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputParamtersSchema.
func (in *InputParamtersSchema) DeepCopy() *InputParamtersSchema {
	if in == nil {
		return nil
	}
	out := new(InputParamtersSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceInfo) DeepCopyInto(out *MaintenanceInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceInfo.
func (in *MaintenanceInfo) DeepCopy() *MaintenanceInfo {
	if in == nil {
		return nil
	}
	out := new(MaintenanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schemas) DeepCopyInto(out *Schemas) {
	*out = *in
	if in.ServiceInstance != nil {
		in, out := &in.ServiceInstance, &out.ServiceInstance
		*out = new(ServiceInstanceSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceBinding != nil {
		in, out := &in.ServiceBinding, &out.ServiceBinding
		*out = new(ServiceBindingSchema)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schemas.
func (in *Schemas) DeepCopy() *Schemas {
	if in == nil {
		return nil
	}
	out := new(Schemas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBindingSchema) DeepCopyInto(out *ServiceBindingSchema) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(InputParamtersSchema)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBindingSchema.
func (in *ServiceBindingSchema) DeepCopy() *ServiceBindingSchema {
	if in == nil {
		return nil
	}
	out := new(ServiceBindingSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfig) DeepCopyInto(out *ServiceBrokerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfig.
func (in *ServiceBrokerConfig) DeepCopy() *ServiceBrokerConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceBrokerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigBinding) DeepCopyInto(out *ServiceBrokerConfigBinding) {
	*out = *in
	if in.ServiceInstance != nil {
		in, out := &in.ServiceInstance, &out.ServiceInstance
		*out = new(ServiceBrokerTemplateList)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceBinding != nil {
		in, out := &in.ServiceBinding, &out.ServiceBinding
		*out = new(ServiceBrokerTemplateList)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigBinding.
func (in *ServiceBrokerConfigBinding) DeepCopy() *ServiceBrokerConfigBinding {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigList) DeepCopyInto(out *ServiceBrokerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceBrokerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigList.
func (in *ServiceBrokerConfigList) DeepCopy() *ServiceBrokerConfigList {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceBrokerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigSpec) DeepCopyInto(out *ServiceBrokerConfigSpec) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(ServiceCatalog)
		(*in).DeepCopyInto(*out)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]ServiceBrokerConfigTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]ServiceBrokerConfigBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigSpec.
func (in *ServiceBrokerConfigSpec) DeepCopy() *ServiceBrokerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplate) DeepCopyInto(out *ServiceBrokerConfigTemplate) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ServiceBrokerConfigTemplateParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplate.
func (in *ServiceBrokerConfigTemplate) DeepCopy() *ServiceBrokerConfigTemplate {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameter) DeepCopyInto(out *ServiceBrokerConfigTemplateParameter) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(ServiceBrokerConfigTemplateParameterDefault)
		(*in).DeepCopyInto(*out)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ServiceBrokerConfigTemplateParameterSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]ServiceBrokerConfigTemplateParameterDestination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameter.
func (in *ServiceBrokerConfigTemplateParameter) DeepCopy() *ServiceBrokerConfigTemplateParameter {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterDefault) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterDefault) {
	*out = *in
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = new(string)
		**out = **in
	}
	if in.Bool != nil {
		in, out := &in.Bool, &out.Bool
		*out = new(bool)
		**out = **in
	}
	if in.Int != nil {
		in, out := &in.Int, &out.Int
		*out = new(int)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterDefault.
func (in *ServiceBrokerConfigTemplateParameterDefault) DeepCopy() *ServiceBrokerConfigTemplateParameterDefault {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterDestination) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterDestination) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterDestination.
func (in *ServiceBrokerConfigTemplateParameterDestination) DeepCopy() *ServiceBrokerConfigTemplateParameterDestination {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSource) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSource) {
	*out = *in
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(string)
		**out = **in
	}
	if in.Parameter != nil {
		in, out := &in.Parameter, &out.Parameter
		*out = new(string)
		**out = **in
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(ServiceBrokerConfigTemplateParameterSourceFormat)
		(*in).DeepCopyInto(*out)
	}
	if in.GeneratePassword != nil {
		in, out := &in.GeneratePassword, &out.GeneratePassword
		*out = new(ServiceBrokerConfigTemplateParameterSourceGeneratePassword)
		(*in).DeepCopyInto(*out)
	}
	if in.GenerateKey != nil {
		in, out := &in.GenerateKey, &out.GenerateKey
		*out = new(ServiceBrokerConfigTemplateParameterSourceGenerateKey)
		(*in).DeepCopyInto(*out)
	}
	if in.GenerateCertificate != nil {
		in, out := &in.GenerateCertificate, &out.GenerateCertificate
		*out = new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificate)
		(*in).DeepCopyInto(*out)
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSource.
func (in *ServiceBrokerConfigTemplateParameterSource) DeepCopy() *ServiceBrokerConfigTemplateParameterSource {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceFormat) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceFormat) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ServiceBrokerConfigTemplateParameterSourceFormatParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceFormat.
func (in *ServiceBrokerConfigTemplateParameterSourceFormat) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceFormat {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceFormatParameter) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceFormatParameter) {
	*out = *in
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(string)
		**out = **in
	}
	if in.Parameter != nil {
		in, out := &in.Parameter, &out.Parameter
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceFormatParameter.
func (in *ServiceBrokerConfigTemplateParameterSourceFormatParameter) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceFormatParameter {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceFormatParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificate) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceGenerateCertificate) {
	*out = *in
	in.Key.DeepCopyInto(&out.Key)
	out.Name = in.Name
	out.Lifetime = in.Lifetime
	if in.AlternativeNames != nil {
		in, out := &in.AlternativeNames, &out.AlternativeNames
		*out = new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames)
		(*in).DeepCopyInto(*out)
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceGenerateCertificate.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificate) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceGenerateCertificate {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]ServiceBrokerConfigTemplateParameterSourceFormatParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = make([]ServiceBrokerConfigTemplateParameterSourceFormatParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificateAltNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA) {
	*out = *in
	in.Key.DeepCopyInto(&out.Key)
	in.Certificate.DeepCopyInto(&out.Certificate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificateCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateName) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceGenerateCertificateName.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateName) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceGenerateCertificateName {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceGenerateCertificateName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateKey) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceGenerateKey) {
	*out = *in
	if in.Bits != nil {
		in, out := &in.Bits, &out.Bits
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceGenerateKey.
func (in *ServiceBrokerConfigTemplateParameterSourceGenerateKey) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceGenerateKey {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceGenerateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerConfigTemplateParameterSourceGeneratePassword) DeepCopyInto(out *ServiceBrokerConfigTemplateParameterSourceGeneratePassword) {
	*out = *in
	if in.Dictionary != nil {
		in, out := &in.Dictionary, &out.Dictionary
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerConfigTemplateParameterSourceGeneratePassword.
func (in *ServiceBrokerConfigTemplateParameterSourceGeneratePassword) DeepCopy() *ServiceBrokerConfigTemplateParameterSourceGeneratePassword {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerConfigTemplateParameterSourceGeneratePassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBrokerTemplateList) DeepCopyInto(out *ServiceBrokerTemplateList) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ServiceBrokerConfigTemplateParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBrokerTemplateList.
func (in *ServiceBrokerTemplateList) DeepCopy() *ServiceBrokerTemplateList {
	if in == nil {
		return nil
	}
	out := new(ServiceBrokerTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceCatalog) DeepCopyInto(out *ServiceCatalog) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceOffering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceCatalog.
func (in *ServiceCatalog) DeepCopy() *ServiceCatalog {
	if in == nil {
		return nil
	}
	out := new(ServiceCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceInstanceSchema) DeepCopyInto(out *ServiceInstanceSchema) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(InputParamtersSchema)
		(*in).DeepCopyInto(*out)
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(InputParamtersSchema)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceInstanceSchema.
func (in *ServiceInstanceSchema) DeepCopy() *ServiceInstanceSchema {
	if in == nil {
		return nil
	}
	out := new(ServiceInstanceSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceOffering) DeepCopyInto(out *ServiceOffering) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DashboardClient != nil {
		in, out := &in.DashboardClient, &out.DashboardClient
		*out = new(DashboardClient)
		**out = **in
	}
	if in.Plans != nil {
		in, out := &in.Plans, &out.Plans
		*out = make([]ServicePlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceOffering.
func (in *ServiceOffering) DeepCopy() *ServiceOffering {
	if in == nil {
		return nil
	}
	out := new(ServiceOffering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePlan) DeepCopyInto(out *ServicePlan) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Bindable != nil {
		in, out := &in.Bindable, &out.Bindable
		*out = new(bool)
		**out = **in
	}
	if in.PlanUpdatable != nil {
		in, out := &in.PlanUpdatable, &out.PlanUpdatable
		*out = new(bool)
		**out = **in
	}
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = new(Schemas)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenanceInfo != nil {
		in, out := &in.MaintenanceInfo, &out.MaintenanceInfo
		*out = new(MaintenanceInfo)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePlan.
func (in *ServicePlan) DeepCopy() *ServicePlan {
	if in == nil {
		return nil
	}
	out := new(ServicePlan)
	in.DeepCopyInto(out)
	return out
}
