= ServiceBrokerConfig Resource Reference

[abstract]
This page describes all fields in the ServiceBrokerConfig Kubernetes resource.

ifdef::env-github[]
:relfileprefix: ../
:imagesdir: https://github.com/couchbase/service-broker/raw/master/documentation/modules/ROOT/assets/images
endif::[]

The `ServiceBrokerConfig` resource is required by each instance of the Service Broker.
Each Service Broker instance requires exactly one `ServiceBrokerConfig` resource.

All attribute names are given in JSON path format as this is the standard Kubernetes notation.

== Resource Types

=== ServiceBrokerConfig Resource

The `ServiceBrokerConfig` resource supports all the regular attributes a core Kubernetes resource contains:

[source,yaml]
----
apiVersion: servicebroker.couchbase.com/v1alpha1
kind: ServiceBrokerConfig
metadata:
  name: couchbase-service-broker
spec: {}
----

==== apiVersion

This attribute defines the Kubernetes API Version of the resource.

* This attribute is required and must be `servicebroker.couchbase.com/v1alpha1`.

==== kind

This attribute defines the Kubernetes resource kind.

* This attribute is required and must be `ServiceBrokerConfig`.

==== metadata.name

This attribute defines the name of the resource.
By default, the Service Broker will look for a `ServiceBrokerConfig` resource named `couchbase-service-broker`.
This can be modified by the `-config` argument to the xref:reference/container.adoc#arguments[Service Broker container].

* This attribute is required and must be a string.

==== spec

This attribute contains the resource specification and controls how the Service Broker functions.
It contains the following objects:

[source,yaml]
----
spec:
  catalog: {}
  bindings: []
  templates: []
----

* This attribute is required and must be an object.

==== spec.catalog

This attribute controls what services are advertised to clients and how clients should behave:
Service catalog use is described by the xref:concepts/catalog.adoc[service catalog concepts documentation].
A service catalog is defined as follows:

[source,yaml]
----
spec:
  catalog:
    services: []
----

* This attribute is required and must be an object.

==== spec.catalog.services

This attribute contains a list of service offerings that the Service Broker can provision.
Service offering use is described by the xref:concepts/catalog.adoc#service-offerings[service offering concepts documentation].
A service offering is configured as follows:

[source,yaml]
----
spec:
  catalog:
    services:
    - name: my-service
      id: 9bb044e2-8733-4ba3-a85e-7f416ca665cb
      description: A service that does foo
      tags:
      - foo
      bindable: true
      metadata:
        foo: bar
      planUpdatable: false
      plans: []
----

* This attribute is required and must be a list of service offerings with at least one member.

==== spec.catalog.services.name

This attribute defines a short service offering name.
The name must be unique across all services advertised by this Service Broker.
The name should be CLI-friendly e.g. no spaces or special characters.

* This attribute is required and must be a non-empty string.

==== spec.catalog.services.id

This attribute defines an ID for a service offering.
The ID must be unique across all service offerings advertised by any service broker.
The ID should be a UUID (generated with `uuidgen`).

* This attribute is required and must be a non-empty string.

==== spec.catalog.services.description

This attribute defines a description of the service offering.

* This attribute is required and must be a non-empty string.

==== spec.catalog.services.tags

This attribute defines an array of tags that allow classification and indexing of a service offering.

* This attribute is optional and must be an array of strings.

==== spec.catalog.services.bindable

This attribute defines whether a service instance created by this service offering can have an associated service binding.
If set to `false` the client should not attempt to bind to a service instance of this service offering type.
The Service Broker will reject binding requests for service offerings whose `bindable` attribute is set to `false`.
This attribute can be overridden on a per-service plan basis by the <<spec-catalog-services-plans-bindable,`spec.catalog.services.plans.bindable`>> attribute.

* This attribute is optional and must be a boolean.
* This attribute defaults to `false`.

==== spec.catalog.services.metadata

This attribute defines an object that contains metadata associated with a service offering.

This attribute is optional and must be an object.

==== spec.catalog.services.planUpdatable

This attribute defines whether a service instance update is capable of changing its plan ID e.g. to facilitate an upgrade.
Changing the plan ID is not currently fully supported so should be set to `false`.
Changing the plan ID should, however, be possible if the underlying Kubernetes resources generated by the Service Broker are the same i.e. same group, version, kind and name.

* This attribute is optional and must be a boolean.
* This attribute defaults to `false`.

==== spec.catalog.services.plans

This attribute defines service plans.
Service offerings are an abstract representation of a service, a service plan is a realization of that service.
Service plan use is described by the xref:concepts/catalog.adoc#service-plans[service plan concepts documentation].
A service plan is defined as follows:

[source,yaml]
----
spec:
  catalog:
    services:
    - plans:
      - name: my-plan
        id: d88f2b01-8fa0-4a0e-b560-3ced84480c8a
        description: A plan that implements a large foo
        metadata:
          foo: bar
        free: false
        bindable: true
        schemas: {}
----

* This attribute is required and must be a list of service plan objects.

==== spec.catalog.services.plans.name

This attribute defines a short service plan name.
The name must be unique across all plans advertised by this service offering.
The name should be CLI-friendly e.g. no spaces or special characters.

* This attribute is required and must be a non-empty string.

==== spec.catalog.services.plans.id

This attribute defines an ID for a service plan.
The ID must be unique across all plans advertised by any service broker.
The ID should be a UUID (generated with `uuidgen`).

* This attribute is required and must be a non-empty string.

==== spec.catalog.services.plans.description

This attribute defines a description of the service plan.

* This attribute is required and must be a non-empty string.

==== spec.catalog.services.plans.metadata

This attribute defines an object that contains metadata associated with a service plan.

* This attribute is optional and must be an object.

==== spec.catalog.services.plans.free

This attribute is an indication to the end user whether creating as service instance of this service plan is free.
If set to `false`, you may wish to also state the cost in the <<spec-catalog-serivces-plans-metadata,`spec.catalog.services.plans.metadata`>> object, for example.

* This attribute is optional and must be a boolean.
* This attribute defaults to `false`.

==== spec.catalog.services.plans.bindable

This attribute defines whether a service instance created by this service plan can have an associated service binding.
If set to `false` the client should not attempt to bind to a service instance of this service offering type.
The Service Broker will reject binding requests for service plans whose `bindable` attribute is set to `false`.
This attribute overrides the service offering default set by the <<spec-catalog-services-bindable,`spec.catalog.services.bindable`>> attribute.

* This attribute is optional and must be a boolean.

==== spec.catalog.services.plans.schemas

This attribute defines schemas that are advertised to the client.
These define the parameter object that can be passed to the Service Broker when performing API operations.
Schema use is described by the xref:concepts/catalog.adoc#json-schemas[JSON schema concepts documentation].
Service plan schemas are defined as follows:

[source,yaml]
----
spec:
  catalog:
    services:
    - plans:
      - schemas:
          serviceInstance:
            create: {}
            update: {}
          serviceBinding:
            create: {}
----

* This attribute is optional and must be an object.

==== spec.catalog.services.plans.schemas.serviceInstance

This attribute defines schemas that can be associated with service instance operations.

* This attribute is optional and must be an object.

==== spec.catalog.services.plans.schemas.serviceInstance.create

This attribute defines a schema that can be associated with service instance creation.

* This attribute is optional and must be an object.
* This attribute is described in more detail in the <<input-parameter-schema,input parameter schema>> reference documentation.

==== spec.catalog.services.plans.schemas.serviceInstance.update

This attribute defines a schema that can be associated with a service instance update.

* This attribute is optional and must be an object.
* This attribute is described in more detail in the <<input-parameter-schema,input parameter schema>> reference documentation.

==== spec.catalog.services.plans.schemas.serviceBinding

This attribute defines schemas that can be associated with service binding operations.

* This attribute is optional and must be an object.

==== spec.catalog.services.plans.schemas.serviceBinding.create

This attribute defines a schema that can be associated with service binding creation.

* This attribute is optional and must be an object.
* This attribute is described in more detail in the <<input-parameter-schema,input parameter schema>> reference documentation.

==== spec.bindings

This attribute defines how service plans are mapped to configuration templates.
Configuration binding use is described in the xref:concepts/bindings.adoc[configuration bindings concepts documentation].
Configuration bindings are defined as follows:

[source,yaml]
----
spec:
  bindings:
  - name: my-binding
    service: my-service
    plan: my-plan
    serviceInstance: {}
    serviceBindings: {}
----

* This attribute is required and must be an array of configuration binding objects.

==== spec.bindings.name

This attribute defines a human-readable name for the configuration binding.
The name is primarily used to provide debugging hints.

* The attribute is required and must be a string.

==== spec.bindings.service

This attribute refers to the <<spec-catalog-services-name,name of the service offering>> this configuration binding is bound to.
This name must reference the name of a service offering defined in the service catalog.

* This attribute is required and must be a string.

==== spec.bindings.plan

This attribute refers to the <<spec-catalog-services-plans-name,name of the service plan>> this configuration binding is bound to.
This name must reference the name of a service plan defined in the service catalog.
This plan name must be referenced by one configuration binding.

* This attribute is required and must be a string.

==== spec.bindings.serviceInstance

This attribute defines the parameters and templates that are processed when a service instance is created and updated.

* This attribute is optional and must be an array of objects.
* This attribute is described in more detail in the <<configuration-binding-parameters,configuration binding parameters>> reference.

==== spec.bindings.serviceBinding

This attribute defines the parameters and templates that are processed when a service binding is created.

* This attribute is optional and must be an array of objects.
* This attribute is described in more detail in the <<configuration-binding-parameters,configuration binding parameters>> reference.

==== spec.templates

This attribute defines an array of configuration templates that may be referenced by configuration bindings and configuration parameters.
Configuration template use is described in the xref:concepts/templates.adoc[configuration templates concepts documentation].
Configuration templates are defined as follows:

[source,yaml]
----
spec:
  templates:
  - name: my-template
    template: {}
    parameters: []
    singleton: false
----

* This attribute is optional and must be an array of configuration templates objects.

==== spec.templates.name

This attribute defines a human-readable name for the configuration template.
The name is primarily used to provide debugging hints.

* The attribute is required and must be a string.

==== spec.templates.template

This attribute defines the template to render and patch with configuration parameters.
This must be an object.
Templates referenced by configuration bindings must be Kubernetes resource objects.
Templates referenced by configuration parameters can be any arbitrary object type.

* This attribute is required and must be an object.

==== spec.templates.parameters

This attribute defines an array of configuration parameters to resolve, and potentially patch into the template.
Configuration parameters are processed in order.

* This attribute is optional and must be an array of objects.
* This attribute is covered in more detail in the <<configuration-parameter,configuration parameter>> reference documentation.

==== spec.templates.singleton

This attribute defines whether the rendered Kubernetes resource is a singleton.
When set to `true`, the Service Broker will ignore conflict errors when attempting to create the resource.
Singleton resources cannot be updated.
When set to `false`, the Service Broker will raise an error if a conflict occurs during provisioning.

* This attribute is optional and must be a boolean.
* This attribute defaults to `false`.

== Common Types

Common types are configuration objects that are referenced in multiple places in the `ServiceBrokerConfig` resource.

[#input-parameter-schema]
=== Input Parameter Schema

This object is used to provide a schema for advertising parameters that can be passed to the Service Broker API for creating and updating service instance and service bindings.
Schema use is described by the xref:concepts/catalog.adoc#json-schemas[JSON schema concepts documentation].
Schemas primarily define the structure of the parameter object that can be provided to the Service Broker API.
The Service Broker will also validate parameters--if provided--against the schema.

Schemas must be v4 and above.
Schemas must contain the `$schema` attribute.
Schemas must not contain any external references.
Schemas must not be larger than 64KiB.

Schemas are defined as follows:

[source,yaml]
----
parameters:
  $schema: "http://json-schema.org/draft-04/schema#"
  type: object
  properties:
    size:
      description: "service size"
      type: number
      minimum: 3
      maximum: 9
----

==== parameters

This attribute defines the JSON schema object.

* This attribute is required and must be an object.

[#configuration-binding-parameters]
=== Configuration Binding Parameters

This object contains configuration associated with a configuration binding for service instances and service bindings.
Parameters are processed first, as they define global configuration.
Templates are processed last, as they may reference global configuration created by parameter processing.
Configuration binding parameters are defined as follows:

[source,yaml]
----
parameters: []
templates: []
readinessChecks: []
----

==== parameters

This attribute defines an array of configuration parameters to process.
Configuration parameters are processed in order.
Configuration parameters may only define registry destinations as configuration bindings are not associated with a JSON template.

* This attribute is optional and must be an array of objects.
* This attribute is covered in more detail in the <<configuration-parameter,configuration parameter>> reference documentation.

==== templates

This attribute defines an array of configuration template names to process.
The refers to <<spec-templates-name,configuration template names>> and the referenced configuration template must exist.
Configuration templates are processed in order.

* This attribute is optional and must be an array of string.

==== readinessChecks

This attribute defines any readiness checks that need to be performed on generated resources before allowing the API to declare the service instance ready.
Readiness checks are only allowed for service instances as service bindings do not support asynchronous provisioning.
Readiness checks are only performed on an initial service instance create operation.
Readiness checks are defined as follows:

[source,yaml]
----
readinessChecks:
- name: my-readiness-check
  condition: {}
----

==== readinessChecks.name

This attribute defines a human-readable name for the readiness check.
The name is primarily used to provide debugging hints.

* The attribute is required and must be a string.

==== readinessChecks.condition

This object represents a readiness check against a Kubernetes resource condition.
It references a specific Kubernetes resource type, and should be one defined as a configuration templates.
The namespace and name reference a specific resource of the defined type.
These attributes are configurable to use either a literal name, or reference one pragmatically from a data source such as the registry.
The readiness check waits until a named condition condition exists in the resource status with a defined value.
A condition readiness check is defined as follows:

[source,yaml]
----
readinessChecks:
- condition:
    apiVersion: apps/v1
    kind: Deployment
    namespace: {}
    name: {}
    type: Available
    status: "True"
----

==== readinessChecks.condition.apiVersion

This attribute defines the API version of the desired resource.
This is a combination of the resource group, and resource version.

* This attribute is required and must be a string.

==== readinessChecks.condition.kind

This attribute defines the resource kind of the desired resource.

* This attribute is required and must be a string.

==== readinessChecks.condition.namespace

This attribute defines the namespace the desired resource exists in.

* This attribute is required and must be an object.
* This attribute is described in more detail in the <<string,string>> reference.

==== readinessChecks.condition.name

This attribute defines the name the desired resource has.

* This attribute is required and must be an object.
* This attribute is described in more detail in the <<string,string>> reference.

==== readinessChecks.condition.type

This attribute defines the condition type to match.

* This attribute is required and must be a string.

==== readinessChecks.condition.status

This attribute defines the condition status to match.

* This attribute is required and must be a string.

[#configuration-parameter]
=== Configuration Parameter

This object represents a parameter that reads data, performs a function on that data, then stores the result.
Configuration parameters associated with configuration templates may define any path or registry destination.
Configuration parameters associated with configuration bindings may only define registry destinations.
Configuration parameter use is described in the xref:concepts/parameters.adoc[configuration parameters concepts documentation].
Configuration parameters are defined as follows:

[source,yaml]
----
name: my-parameter
required: false
default: {}
source: {}
destinations: []
----

==== name

This attribute defines a human-readable name for the configuration parameter.
The name is primarily used to provide debugging hints.

* The attribute is required and must be a string.

==== required

This attribute defines whether the parameter is required.
When set to `true` and if the configuration parameter source result is `nil`, then the Service Broker will raise an error.

* This attribute is optional and must be a boolean.
* This attribute defaults to `false`.

==== default

This attribute allows the Service Broker to provide a default value if a configuration parameter source result is `nil`.
This attribute allows a configuration parameter to be defined if an option API parameter is not specified by the end user, or a registry value is not defined.
Defaults are defined as follows:

[source,yaml]
----
default:
  string: my-string
  bool: false
  int: 7
  object:
    foo: bar
----

* This attribute is optional and must be an object.
* One of `string`, `bool`, `int` or `object` must be specified.
* Behavior is undefined if multiple are specified.

==== default.string

This attribute defines a default string value.

* This attribute is optional and must be a string.

==== default.bool

This attribute defines a default boolean value.

* This attribute is optional and must be a boolean.

==== default.int

This attribute defines a default integer value.

* This attribute is optional and must be an integer.

==== default.object

This attribute defines a default object value.

* This attribute is optional and must be an object.

==== source

This attribute defines the configuration parameter source type.
A configuration parameter source may not be specified only when a parameter source default is specified.
Configuration parameter sources are described in more detail in the xref:concepts/parameters.adoc#parameter-sources[configuration parameter source concepts documentation].
Parameter sources are defined as follows:

[source,yaml]
----
source:
  registry: my-key
  parameter: /path/to/my/value
  format: {}
  template: my-template
  generatePassword: {}
  generateKey: {}
  generateCertificate: {}
----

* This attribute is optional and must be an object.
* One of `registry`, `parameter`, `format`, `template`, `generatePassword`, `generateKey`, or `generateCertificate` may be specified.
* Behavior is undefined if multiple are specified.

==== source.registry

This attribute causes the Service Broker to source a value from the registry associated with the service instance or service binding.
If the specified registry key does not exist, the result will be `nil`.

* This attribute is optional and must be a string.

==== source.parameter

This attribute causes the Service Broker to source a value from the user-specified service instance or service binding request parameters.
If the specified JSON pointer does not exist, the result will be `nil`.

* This attribute is optional and must be a string.

==== source.format

This attribute causes the Service Broker to lookup a set of parameters then apply them to a formatting string.
If any parameter to the formatting operation is `nil`, the result will also be `nil`.
A formatting operation is analogous to `sprintf`.
A formatting operation contains no error checking at present e.g. passing an integer to a `%s` will have an undefined result.
A formatting operation is defined as follows:

[source,yaml]
----
source:
  format:
    string: my-format-%v
    parameters: []
----

==== source.format.string

This attribute defines a https://golang.org/pkg/fmt/[golang formatting string^].

* This attribute is required and must be a string.

==== source.format.parameters

This attribute defines an array of accessors that provide arguments to the format string.

* This attribute is required and must be an array of objects.
* This attribute is covered in more detail in the <<accessor,accessor>> reference documentation.

==== source.template

This attribute causes the Service Broker to perform a recursive template processing.
The refers to a <<spec-templates-name,configuration template name>> and the referenced configuration template must exist.

* This attribute is optional and must be a string.

==== source.generatePassword

This attribute causes the Service Broker to generate a cryptographically secure random password.
Password generation is defined as follows:

[source,yaml]
----
source:
  generatePassword:
    length: 7
    dictionary: abcde
----

* This attribute is optional and must be an object.

==== source.generatePassword.length

This attribute defines the length of the password to generate.

* This attribute is required and must be an integer greater than or equal to 1.

==== source.generatePassword.dictionary

This attribute defines is the dictionary to use when generating a password.

* This attribute is optional and must be a string.
* This attribute defaults to `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`.

==== source.generateKey

This attribute causes the Service Broker to generate a PEM encoded private key.
RSA, ECDSA and ED25519 are all fully supported.
Password protected private keys are not currently supported.
Private key generation is defined as follows:

[source,yaml]
----
source:
  generateKey:
    type: RSA
    encoding: PKCS8
    bits: 2048
----

==== source.generateKey.type

This attribute defines the key type to generate.

* This attribute is required and must be one of `RSA`, `EllipticP224`, `EllipticP256`, `EllipticP384`, `EllipticP521` or `ED25519`.

==== source.generateKey.encoding

This attribute defines the PEM and ASN.1 encoding of the private key.
PKCS#1 can only be used with RSA private keys.
PKCS#8 can be used with any private key type.
SEC 1 can only be used with elliptic private keys.

* This attribute is required and must be one of `PKCS1`, `PKCS8` or `SEC1`.

==== source.generateKey.bits

This attribute defined the private key size in bits.
It is required for RSA private keys and ignored for all other private key types.

* This attribute is optional and must be an integer greater than or equal to 1.

==== source.generateCertificate

This attribute causes the Service Broker to generate an X.509 certificate from a PEM encoded private key.
Only RSA and ECDSA private keys are supported.
Certificates specified without a CA will be self-signed, rather than signed by the CA.

[source,yaml]
----
source:
  generateCertificate:
    key: {}
    subject:
      commonName: My Certificate
    lifetime: "8760h"
    usage: server
    alternativeNames:
      dns: []
      email: []
    ca:
      key: {}
      certificate: {}
  template: my-template
----

* This attribute is optional and must be an object.

==== source.generateCertificate.key

This attribute references a PEM encoded private key with an accessor.

* This attribute is required and must be an object.
* This attribute is covered in more detail in the <<accessor,accessor>> reference documentation.

==== source.generateCertificate.subject

This attribute defines the certificate subject.

* This attribute is required and must be an object.

==== source.generateCertificate.subject.commonName

This attribute defines the certificate subject common name (CN).

* This attribute is required and must be a string.

==== source.generateCertificate.lifetime

This attribute defines the certificate lifetime.
A certificate is generated with the "not valid before" attribute to the current time.
The lifetime sets the "not valid after" attribute to the current time plus the lifetime.
The format of lifetime is defined by the https://golang.org/pkg/time/#ParseDuration[golang duration specification^].

* This attribute is required and must be a string.

==== source.generateCertificate.usage

This attribute defines the certificate usage.
Specifically this controls the X.509 "is CA", "key usage" and "extended key usage" attributes.

* This attribute is required and must be one of `CA`, `Server` or `Client`.

==== source.generateCertificate.alternativeNames

This attribute defines any subject alternative names (SANs) to add to the certificate.
Only DNS and e-mail SANs are allowed, IP addresses in Kubernetes--for example--are unstable there for make no sense.

* This attribute is optional and must be an object.

==== source.generateCertificate.alternativeNames.dns

This attribute defines an array of DNS SANs to add to the certificate.
SANs are collected using accessors, any that resolve to `nil` are not added to the certificate.
DNS SANs should only be used with certificates with the `server` usage.

* This attribute is optional and must be an array.
* This attribute is covered in more detail in the <<accessor,accessor>> reference documentation.

==== source.generateCertificate.alternativeNames.email

This attribute defines an array of EMAIL SANs to add to the certificate.
SANs are collected using accessors, any that resolve to `nil` are not added to the certificate.
EMAIL SANs should only be used with certificates with the `client` usage.

* This attribute is optional and must be an array.
* This attribute is covered in more detail in the <<accessor,accessor>> reference documentation.

==== source.generateCertificate.ca

This attribute defines a certificate authority (CA) certificate and private key pair to sign the certificate with.

* This attribute is optional and must be an object.

==== source.generateCertificate.ca.key

This attribute defines the PEM encoded CA private key to use with an accessor.

* This attribute is required and must be an object.
* This attribute is covered in more detail in the <<accessor,accessor>> reference documentation.

==== source.generateCertificate.ca.certificate

This attribute defines the X.509 CA certificate to use with an accessor.

* This attribute is required and must be an object.
* This attribute is covered in more detail in the <<accessor,accessor>> reference documentation.

==== destinations

This attribute defines a list of where to store non-`nil` configuration parameter results.
Configuration parameter destinations are described in more detail in the xref:concepts/parameters.adoc#parameter-destinations[configuration parameter destination concepts documentation].
Configuration parameter destinations may be stored to either the registry or a path per entry, but not both, behavior is undefined in this case.
Configuration parameter destinations are defined as follows:

[source,yaml]
----
destinations:
- registry: my-key
  path: /attribute/to/add
----

* This attribute is requires and must be a non-empty array of objects.

==== destinations.registry

This attribute defines a registry key to store the result to.
A registry destination may be used at any time.

* This attribute is optional and must be a string.

==== destinations.path

This attribute defines a JSON pointer to an attribute to to store the value within a configuration template.
Destination paths cannot be used for configuration parameters associated with configuration bindings.

* This attribute is optional and must be a string.

[#accessor]
=== Accessor

This object is used by parameter sources to read configuration data dynamically from one of the available data sources.
Only one of `registry` or `parameter` should be specified, the result is undefined otherwise.

[source,yaml]
----
registry: my-key
parameter: /path/to/my/value
----

==== registry

This attribute causes the Service Broker to source a value from the registry associated with the service instance or service binding.

* This attribute is optional and must be a string.

==== parameter

This attribute causes the Service Broker to source a value from the user-specified service instance or service binding request parameters.

* This attribute is optional and must be a string.

[#string]
=== String

This object is a specialization of the <<accessor,accessor>> type that enforces type.
It also allows a literal string value to be specified.
Only one of `registry`, `parameter` or `string` can be specified, the result is undefined otherwise.

[source,yaml]
----
registry: my-key
parameter: /path/to/my/value
string: my-string
----

==== registry

This attribute causes the Service Broker to source a value from the registry associated with the service instance or service binding.

* This attribute is optional and must be a string.

==== parameter

This attribute causes the Service Broker to source a value from the user-specified service instance or service binding request parameters.

* This attribute is optional and must be a string.

==== string

This attribute provides a literal string value.

* This attribute is optional and must be a string.
