= Package Downloads

[abstract]
This page details package options and how to get them.

ifdef::env-github[]
:relfileprefix: ../
:imagesdir: https://github.com/couchbase/service-broker/raw/master/documentation/modules/ROOT/assets/images
endif::[]

== Official Images

Official Docker images are built automatically per-release.
Images can be found on https://hub.docker.com/r/couchbase/service-broker[Docker Hub^].
Take a note of the Docker tag you wish to use--we recommend the latest as it contains all the latest bug fixes and features.

If you want to download the official packages and build your own container images, keep reading.
Otherwise, skip ahead to xref:install/kubernetes.adoc[Creating the Service Broker Service].

== Official Packages

Official packages are automatically built by the Continuous Integration system.
These are hosted on https://github.com/couchbase/service-broker/releases[GitHub^].

It is recommended that you use the most recent release to take advantage of newer functionality and bug fixes.

DEB and RPM archives are provided for Debian and Red Hat derivatives and should be used where possible as they are version controlled by the package manager.

ZIP and TAR archives are also provided for users of any other operating system.
They contain files that will be installed under `usr/share/couchbase-service-broker`, therefore may be extracted to `/` on UNIX like systems.
For example:

[source,console]
----
sudo tar xf -C / couchbase-service-broker-0.0.0-99999.tar.gz
----

.Using Non-Standard Installation Paths
[IMPORTANT]
====
If installing into a non-standard directory this will affect the paths described in the following sections.
Replace any instances of `/usr/share/couchbase-service-broker` with the location of your unpacked archive.
====

== Next Steps

* xref:install/container.adoc[Creating Container Images]
