= Prerequisites

[abstract]
This page details the platform and software requirements for running the Service Broker.

ifdef::env-github[]
:relfileprefix: ../
:imagesdir: https://github.com/couchbase/service-broker/raw/master/documentation/modules/ROOT/assets/images
endif::[]

== Platform Requirements

These are the basic platform requirements that you will need for the various setup steps.

=== Kubernetes

The following platforms are supported:

* Kubernetes 1.17+
* Red Hat OpenShift 4.4+

In general, any Kubernetes distribution based on a supported version should work.

=== Service Catalog

The Service Broker is recommended for use with the https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/[Kubernetes Service Catalog^].

Installation instructions can be found in the https://kubernetes.io/docs/tasks/service-catalog/[official documentation].

As the Service Broker is standards based, any version of the Service Catalog supporting the Open Service Broker API version 2.13+ is supported.

== Build Requirements

To get up and running you will need to install on your local machine:

* docker

== Next Steps

* xref:install/packages.adoc[Package Downloads]
